CREATE TABLE IF NOT EXISTS users (
    id INT UNIQUE NOT NULL PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);