CREATE TABLE IF NOT EXISTS organizations(
    id SERIAL UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    description TEXT,
    json_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);