CREATE TABLE IF NOT EXISTS clusters(
    id SERIAL NOT NULL UNIQUE PRIMARY KEY,
    org_id INT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);