CREATE TABLE IF NOT EXISTS houses (
    id SERIAL NOT NULL PRIMARY KEY,
    addr VARCHAR NOT NULL,
    location GEOMETRY(Point, 4326),
    json_data JSONB DEFAULT Null,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);