CREATE TABLE IF NOT EXISTS notifications(
    id SERIAL UNIQUE NOT NULL PRIMARY KEY,
    cluster_id INT NOT NULL REFERENCES clusters(id) ON DELETE CASCADE ON UPDATE CASCADE,
    source_id VARCHAR NOT NULL,
    priority INT DEFAULT 5,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);