CREATE TABLE IF NOT EXISTS users_houses(
    user_id INT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    house_id INT NOT NULL REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (user_id, house_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);