CREATE TABLE IF NOT EXISTS notifications_tags (
    notification_id INT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE ON UPDATE CASCADE,
    tag_id INT NOT NULL REFERENCES tags(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);