CREATE TABLE IF NOT EXISTS clusters_houses(
    cluster_id INT NOT NULL REFERENCES clusters(id) ON DELETE CASCADE ON UPDATE CASCADE,
    house_id INT NOT NULL REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (cluster_id, house_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);