services:
    bot:
        image: registry.gitlab.com/lamentoeldi/etu-bot:dev
        build:
            context: .
            dockerfile: build/Dockerfile
        env_file:
            -   ./etc/bot/.env
        depends_on:
            -   postgres
        restart: on-failure
    postgres:
        image: postgis/postgis:17-3.6-alpine
        platform: linux/amd64
        env_file:
            -   ./etc/postgres/.env
        ports:
            -   "5432:5432"