// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

type AssignTagsBadRequest Error

func (*AssignTagsBadRequest) assignTagsRes() {}

type AssignTagsInternalServerError Error

func (*AssignTagsInternalServerError) assignTagsRes() {}

// Ref: #/components/schemas/AssignTagsRequest
type AssignTagsRequest struct {
	// Текст сообщения пользователя (объявление, заявка,
	// обращение).
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *AssignTagsRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *AssignTagsRequest) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/AssignTagsResponse
type AssignTagsResponse struct {
	// Присвоенные теги. Пустой массив — тема не определена.
	Data []string `json:"data"`
}

// GetData returns the value of Data.
func (s *AssignTagsResponse) GetData() []string {
	return s.Data
}

// SetData sets the value of Data.
func (s *AssignTagsResponse) SetData(val []string) {
	s.Data = val
}

func (*AssignTagsResponse) assignTagsRes() {}

type AssignTagsServiceUnavailable Error

func (*AssignTagsServiceUnavailable) assignTagsRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// Машинно-читаемый код ошибки.
	Code ErrorCode `json:"code"`
	// Человекочитаемое описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() ErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val ErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// Машинно-читаемый код ошибки.
type ErrorCode string

const (
	ErrorCodeInvalidRequest   ErrorCode = "invalid_request"
	ErrorCodeInternalError    ErrorCode = "internal_error"
	ErrorCodeModelUnavailable ErrorCode = "model_unavailable"
)

// AllValues returns all ErrorCode values.
func (ErrorCode) AllValues() []ErrorCode {
	return []ErrorCode{
		ErrorCodeInvalidRequest,
		ErrorCodeInternalError,
		ErrorCodeModelUnavailable,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorCodeInvalidRequest:
		return []byte(s), nil
	case ErrorCodeInternalError:
		return []byte(s), nil
	case ErrorCodeModelUnavailable:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorCode) UnmarshalText(data []byte) error {
	switch ErrorCode(data) {
	case ErrorCodeInvalidRequest:
		*s = ErrorCodeInvalidRequest
		return nil
	case ErrorCodeInternalError:
		*s = ErrorCodeInternalError
		return nil
	case ErrorCodeModelUnavailable:
		*s = ErrorCodeModelUnavailable
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/HealthResponse
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthResponse) GetStatus() HealthResponseStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthResponse) SetStatus(val HealthResponseStatus) {
	s.Status = val
}

type HealthResponseStatus string

const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// AllValues returns all HealthResponseStatus values.
func (HealthResponseStatus) AllValues() []HealthResponseStatus {
	return []HealthResponseStatus{
		HealthResponseStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthResponseStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthResponseStatus) UnmarshalText(data []byte) error {
	switch HealthResponseStatus(data) {
	case HealthResponseStatusOk:
		*s = HealthResponseStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
