// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AssignTags implements assignTags operation.
//
// Принимает текст сообщения и возвращает список
// тематических тегов (например, `покупка`, `гитара`).
// Список может быть пустым, если тему определить не
// удалось — вызывающая сторона сама решает, что делать
// дальше.
//
// POST /api/v1/tags/assign
func (UnimplementedHandler) AssignTags(ctx context.Context, req *AssignTagsRequest) (r AssignTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// Используется ботом и оркестратором, чтобы убедиться,
// что сервис жив.
//
// GET /health
func (UnimplementedHandler) HealthCheck(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}
