// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AssignTags implements assignTags operation.
	//
	// Принимает текст сообщения и возвращает список
	// тематических тегов (например, `покупка`, `гитара`).
	// Список может быть пустым, если тему определить не
	// удалось — вызывающая сторона сама решает, что делать
	// дальше.
	//
	// POST /api/v1/tags/assign
	AssignTags(ctx context.Context, req *AssignTagsRequest) (AssignTagsRes, error)
	// HealthCheck implements healthCheck operation.
	//
	// Используется ботом и оркестратором, чтобы убедиться,
	// что сервис жив.
	//
	// GET /health
	HealthCheck(ctx context.Context) (*HealthResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
